#!/usr/bin/env python3
"""Check generated cargo-dist installer mappings for the published targets.

The templates live under target/ and are generated by cargo-dist. This check
does not download, upload, install, or contact a provider; it only prevents the
generated templates from silently selecting an unavailable or wrongly named asset.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


EXPECTED_SHELL = {
    "aarch64-apple-darwin": "growthlab-aarch64-apple-darwin.tar.gz",
    "x86_64-apple-darwin": "growthlab-x86_64-apple-darwin.tar.gz",
    "aarch64-unknown-linux-musl-static": "growthlab-aarch64-unknown-linux-musl.tar.gz",
    "x86_64-unknown-linux-musl-static": "growthlab-x86_64-unknown-linux-musl.tar.gz",
    "x86_64-pc-windows-gnu": "growthlab-x86_64-pc-windows-gnu.zip",
}

EXPECTED_POWERSHELL = {
    "x86_64-pc-windows-gnu": "growthlab-x86_64-pc-windows-gnu.zip",
}


def shell_case(source: str, triple: str) -> str:
    marker = f'        "{triple}")'
    starts = [match.start() for match in re.finditer(re.escape(marker), source)]
    if not starts:
        raise AssertionError(f"shell template has no {triple} archive case")
    start = starts[-1]
    end = source.find('\n        "', start + len(marker))
    return source[start:] if end < 0 else source[start:end]


def powershell_artifact(source: str, triple: str) -> str:
    match = re.search(
        rf'"{re.escape(triple)}"\s*=\s*@\{{\s*"artifact_name"\s*=\s*"([^"]+)"',
        source,
        re.S,
    )
    if not match:
        raise AssertionError(f"PowerShell template has no {triple} platform entry")
    return match.group(1)


def check(args: argparse.Namespace) -> None:
    shell = args.shell.read_text(encoding="utf-8")
    powershell = args.powershell.read_text(encoding="utf-8")
    for triple, artifact in EXPECTED_SHELL.items():
        if artifact not in shell_case(shell, triple):
            raise AssertionError(f"shell {triple} does not select {artifact}")

    for triple, artifact in EXPECTED_POWERSHELL.items():
        actual = powershell_artifact(powershell, triple)
        if actual != artifact:
            raise AssertionError(f"PowerShell {triple} selects {actual}, expected {artifact}")

    if args.check_shell:
        subprocess.run(["sh", "-n", str(args.shell)], check=True)

    print("installer_template_mapping_ok")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shell", type=Path, default=Path("target/distrib/growthlab-installer.sh"))
    parser.add_argument("--powershell", type=Path, default=Path("target/distrib/growthlab-installer.ps1"))
    parser.add_argument("--check-shell", action="store_true", help="also run sh -n on the shell template")
    args = parser.parse_args()
    for path in (args.shell, args.powershell):
        if not path.is_file() or path.is_symlink():
            parser.error(f"template is missing or symlinked: {path}")
    try:
        check(args)
    except (AssertionError, OSError, subprocess.CalledProcessError) as error:
        print(f"installer template check failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
